include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NGRProxy
LUCI_DEPENDS:=+luci-compat +nginx-ssl +nginx-mod-stream +bash
LUCI_PKGARCH:=all
PKG_LICENSE:=GPL-3.0-only

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
