#!/bin/sh

set -eu

. /lib/functions.sh

HTTP_TMP="/tmp/ngrproxy.http.conf"
STREAM_TMP="/tmp/ngrproxy.stream.conf"
HTTP_TARGET="/tmp/ngrproxy/generated.http.conf"
STREAM_TARGET="/tmp/ngrproxy/generated.stream.conf"

HTTP_INCLUDE_DIR="$(uci -q get ngrproxy.settings.http_include_dir || true)"
STREAM_INCLUDE_DIR="$(uci -q get ngrproxy.settings.stream_include_dir || true)"
[ -n "$HTTP_INCLUDE_DIR" ] || HTTP_INCLUDE_DIR="/etc/nginx/conf.d"
[ -n "$STREAM_INCLUDE_DIR" ] || STREAM_INCLUDE_DIR="/etc/nginx/stream.d"

mkdir -p "$HTTP_INCLUDE_DIR" "$STREAM_INCLUDE_DIR" /tmp

: > "$HTTP_TMP"
: > "$STREAM_TMP"

echo "# autogenerated by ngrproxy" >> "$HTTP_TMP"
echo "# autogenerated by ngrproxy" >> "$STREAM_TMP"

require_file() {
	local path="$1"
	local label="$2"
	[ -f "$path" ] || {
		echo "Missing ${label}: ${path}" >&2
		exit 1
	}
}

print_http_acl_allow() {
	local entry="$1"
	echo "        allow ${entry};"
}

print_stream_acl_allow() {
	local entry="$1"
	echo "    allow ${entry};"
}

append_http_host() {
	local section="$1"
	local enabled domain listen_http listen_https tls_cert tls_key
	local upstream_scheme upstream_target upstream_host upstream_port upstream_sni upstream_ca acl_deny_all

	config_get enabled "$section" enabled "1"
	[ "$enabled" = "1" ] || return 0

	config_get domain "$section" domain ""
	config_get listen_http "$section" listen_http "0"
	config_get listen_https "$section" listen_https "1"
	config_get tls_cert "$section" tls_cert ""
	config_get tls_key "$section" tls_key ""
	config_get upstream_scheme "$section" upstream_scheme "http"
	config_get upstream_target "$section" upstream_target "manual"
	config_get upstream_host "$section" upstream_host ""
	config_get upstream_port "$section" upstream_port ""
	config_get upstream_sni "$section" upstream_sni ""
	config_get upstream_ca "$section" upstream_ca ""
	config_get acl_deny_all "$section" acl_deny_all "0"

	[ -n "$domain" ] || { echo "http_host[$section]: domain is required" >&2; exit 1; }
	if [ "$upstream_target" != "manual" ] && [ -n "$upstream_target" ]; then
		upstream_host="$upstream_target"
	fi
	[ -n "$upstream_host" ] || { echo "http_host[$section]: upstream_host is required" >&2; exit 1; }
	[ -n "$upstream_port" ] || upstream_port="8080"

	if [ "$listen_http" != "1" ] && [ "$listen_https" != "1" ]; then
		echo "http_host[$section]: enable listen_http or listen_https" >&2
		exit 1
	fi

	if [ "$listen_https" = "1" ]; then
		[ -n "$tls_cert" ] || { echo "http_host[$section]: tls_cert required for HTTPS listener" >&2; exit 1; }
		[ -n "$tls_key" ] || { echo "http_host[$section]: tls_key required for HTTPS listener" >&2; exit 1; }
		require_file "$tls_cert" "certificate"
		require_file "$tls_key" "private key"
	fi

	if [ "$upstream_scheme" = "https" ]; then
		[ -n "$upstream_sni" ] || { echo "http_host[$section]: upstream_sni required for HTTPS upstream" >&2; exit 1; }
		[ -n "$upstream_ca" ] || { echo "http_host[$section]: upstream_ca required for HTTPS upstream verification" >&2; exit 1; }
		require_file "$upstream_ca" "upstream CA bundle"
	fi

	{
		echo "server {"
		[ "$listen_http" = "1" ] && echo "    listen 80;"
		if [ "$listen_https" = "1" ]; then
			echo "    listen 443 ssl http2;"
			echo "    ssl_certificate ${tls_cert};"
			echo "    ssl_certificate_key ${tls_key};"
		fi
		echo "    server_name ${domain};"
		echo "    location / {"
		config_list_foreach "$section" acl_allow print_http_acl_allow
		[ "$acl_deny_all" = "1" ] && echo "        deny all;"
		echo "        proxy_set_header Host \$host;"
		echo "        proxy_set_header X-Real-IP \$remote_addr;"
		echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
		echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
		if [ "$upstream_scheme" = "https" ]; then
			echo "        proxy_ssl_server_name on;"
			echo "        proxy_ssl_name ${upstream_sni};"
			echo "        proxy_ssl_verify on;"
			echo "        proxy_ssl_trusted_certificate ${upstream_ca};"
		fi
		echo "        proxy_pass ${upstream_scheme}://${upstream_host}:${upstream_port};"
		echo "    }"
		echo "}"
		echo
	} >> "$HTTP_TMP"
}

append_stream_host() {
	local section="$1"
	local enabled listen_addr listen_port upstream_target upstream_host upstream_port
	local acl_deny_all listen_proxy_protocol send_proxy_protocol

	config_get enabled "$section" enabled "1"
	[ "$enabled" = "1" ] || return 0

	config_get listen_addr "$section" listen_addr "0.0.0.0"
	config_get listen_port "$section" listen_port ""
	config_get upstream_target "$section" upstream_target "manual"
	config_get upstream_host "$section" upstream_host ""
	config_get upstream_port "$section" upstream_port ""
	config_get acl_deny_all "$section" acl_deny_all "0"
	config_get listen_proxy_protocol "$section" listen_proxy_protocol "0"
	config_get send_proxy_protocol "$section" send_proxy_protocol "0"

	[ -n "$listen_port" ] || { echo "stream_host[$section]: listen_port is required" >&2; exit 1; }
	if [ "$upstream_target" != "manual" ] && [ -n "$upstream_target" ]; then
		upstream_host="$upstream_target"
	fi
	[ -n "$upstream_host" ] || { echo "stream_host[$section]: upstream_host is required" >&2; exit 1; }
	[ -n "$upstream_port" ] || { echo "stream_host[$section]: upstream_port is required" >&2; exit 1; }

	{
		echo "server {"
		echo -n "    listen ${listen_addr}:${listen_port}"
		[ "$listen_proxy_protocol" = "1" ] && echo -n " proxy_protocol"
		echo ";"
		config_list_foreach "$section" acl_allow print_stream_acl_allow
		[ "$acl_deny_all" = "1" ] && echo "    deny all;"
		echo "    proxy_pass ${upstream_host}:${upstream_port};"
		[ "$send_proxy_protocol" = "1" ] && echo "    proxy_protocol on;"
		echo "    ssl_preread on;"
		echo "}"
		echo
	} >> "$STREAM_TMP"
}

config_load ngrproxy
config_foreach append_http_host http_host
config_foreach append_stream_host stream_host

mv "$HTTP_TMP" "$HTTP_TARGET"
mv "$STREAM_TMP" "$STREAM_TARGET"
ln -sf "$HTTP_TARGET" "$HTTP_INCLUDE_DIR/zz-ngrproxy-generated.conf"
ln -sf "$STREAM_TARGET" "$STREAM_INCLUDE_DIR/zz-ngrproxy-generated.conf"

nginx -t >/tmp/ngrproxy.nginx-test.log 2>&1
